### ISSUE TITLE
大纲列表圆点位移导致逻辑线错位，怎么修改？

### ISSUE THREAD

**Issue by kubulo** [ttytm/logseq-allday-theme#20] opened 2023-05-17 13:59 UTC
<img width="798" alt="竖线_2023-05-16_22-49-42" src="https://github.com/tobealive/logseq-allday-theme/assets/74105898/99e2fa76-ae48-42f7-96d2-7848970c63de">

大佬，在修改custom.css时不小心修改了什么代码，导致`大纲逻辑线错位`（项目列表圆点偏右了），如何恢复一致性，需要在custom.css修改哪个代码？

**Comment by tobealive** [comment] 2023-05-23 17:57
Hey @kubulo ,

Thanks, for reaching out.

Nice to see logseq evolving. With the latest version 0.9.7 I'm running into issues testing it and loading graphs. I check on this issue soon!

**Comment by ttytm** [comment] 2023-10-19 09:02
Gonna close this as for now as I cannot reproduce the issue. 

If you still run into the issue, please leave a message here with information about the Logseq version and operating system you are using provided. Best regards.

**Closed by ttytm** 2023-10-19 09:02 UTC
